### ISSUE TITLE
问题咨询

### ISSUE THREAD

**Issue by yzfshuijing** [jx-sec/jxwaf#1]
您好，您的说明中“内置的语义分析引擎配合机器学习引擎可以避免传统WAF规则叠加太多导致速度变慢的问题”。见简要介绍下实现这块逻辑的实现架构以及具体代码位置吗？
不胜感激。。。

**Comment by jx-sec** [comment]
语义分析引擎使用的是libinjection，代码在https://github.com/client9/libinjection。语义分析引擎比正则快就快在，里面耗性能的其实就一二分查找算法，所以就算他内置了8000多种识别模式，对性能也几乎没有影响。如果把8000多种模式换成正则匹配，那性能肯定是要大打折扣的。具体你去看他代码就明白。机器学习目前集成的是svm算法，直接嵌入WAF.具体代码还在整理，后续会考虑放出来。一些细节你可以看我的文章  锦衣盾-开源WEB应用防火墙介绍  http://www.freebuf.com/column/167984.html

**Comment by yzfshuijing** [comment]
好的，基本了解了，多谢！
