### ISSUE TITLE
ubuntu下无法安装

### ISSUE THREAD

**Issue by Maskhe** [jx-sec/jxwaf#10]
报如下错误，不知道怎么解决
make[2]: 离开目录“/home/axin/下载/jxwaf-master/libmaxminddb-1.3.2”
make[1]: 离开目录“/home/axin/下载/jxwaf-master/libmaxminddb-1.3.2”
cp: 无法创建普通文件'/opt/jxwaf/lualib/libmaxminddb.so': 没有那个文件或目录
install_waf.sh: 25: install_waf.sh: cmake: not found
make: *** 没有指明目标并且找不到 makefile。 停止。
cp: 无法获取'build/lib/liblog_c_sdk.so.2.0.0' 的文件状态(stat): 没有那个文件或目录
install_waf.sh: 28: install_waf.sh: /opt/jxwaf/nginx/sbin/nginx: not found

**Comment by jx-sec** [comment]
目前仅提供centos7支持,请通过centos7安装,或者使用docker版本

**Comment by Maskhe** [comment]
> 目前仅提供centos7支持,请通过centos7安装,或者使用docker版本

好的，谢谢回复
