### ISSUE TITLE
多久才更新使用文档啊

### ISSUE THREAD

**Issue by Maskhe** [jx-sec/jxwaf#11]
之前看到freebuf上chenjc放的钓鱼网站实现,自己想试试jxwaf,但是发现文章中有一些细节没有被提及.希望早日看到使用文档

**Comment by jx-sec** [comment]
mark

**Comment by starnightcyber** [comment]
已经过去了好久好久

**Comment by jx-sec** [comment]
在忙新功能开发～～～，这个优先级不高，所以还在todo，文档群里有更新个初步的文档，可以先看，有问题群里提问就可以。

**Comment by jx-sec** [comment]
正式版本发布,文档已更新
