### ISSUE TITLE
centos7安装出错

### ISSUE THREAD

**Issue by Maskhe** [jx-sec/jxwaf#12]
emmmm,在centos7上安装不成功,一开始是缺各种依赖文件,安装了就好了,但是后面报的这个错我就不知道怎么解决了

cp: 无法创建普通文件"/opt/jxwaf/lualib/libmaxminddb.so": 没有那个文件或目录
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
CRYPTO_LIBRARY
    linked by target "log_post_logs_sample" in directory /tmp/jxwaf/aliyun-log-c-sdk-lite/sample
    linked by target "log_producer_benchmark" in directory /tmp/jxwaf/aliyun-log-c-sdk-lite/sample
    linked by target "log_producer_sample" in directory /tmp/jxwaf/aliyun-log-c-sdk-lite/sample
    linked by target "video_frame_producer_sample" in directory /tmp/jxwaf/aliyun-log-c-sdk-lite/sample
SSL_LIBRARY
    linked by target "log_post_logs_sample" in directory /tmp/jxwaf/aliyun-log-c-sdk-lite/sample
    linked by target "log_producer_benchmark" in directory /tmp/jxwaf/aliyun-log-c-sdk-lite/sample
    linked by target "log_producer_sample" in directory /tmp/jxwaf/aliyun-log-c-sdk-lite/sample
    linked by target "video_frame_producer_sample" in directory /tmp/jxwaf/aliyun-log-c-sdk-lite/sample
ZLIB_LIBRARY
    linked by target "log_post_logs_sample" in directory /tmp/jxwaf/aliyun-log-c-sdk-lite/sample
    linked by target "log_producer_benchmark" in directory /tmp/jxwaf/aliyun-log-c-sdk-lite/sample
    linked by target "log_producer_sample" in directory /tmp/jxwaf/aliyun-log-c-sdk-lite/sample
    linked by target "video_frame_producer_sample" in directory /tmp/jxwaf/aliyun-log-c-sdk-lite/sample

-- Configuring incomplete, errors occurred!
See also "/tmp/jxwaf/aliyun-log-c-sdk-lite/CMakeFiles/CMakeOutput.log".
make: *** 没有指明目标并且找不到 makefile。 停止。
cp: 无法获取"build/lib/liblog_c_sdk.so.2.0.0" 的文件状态(stat): 没有那个文件或目录
install_waf.sh:行28: /opt/jxwaf/nginx/sbin/nginx: 没有那个文件或目录

**Comment by m1911** [comment]
他那个 安装脚本里面 都包含了 依赖了啊

**Comment by jx-sec** [comment]
你可以手动执行安装脚本的语句,看具体哪里出问题,如果是环境问题,建议你用docker版本
