### ISSUE TITLE
节点无法接入

### ISSUE THREAD

**Issue by Oceanlotus** [jx-sec/jxwaf#16]
节点无法接入控制端，出现错误
failed to request: update2.jxwaf.com could not be resolved (110: Operation timed out), context: ngx.timer 
服务器位于美国  ping与curl均正常

**Comment by jx-sec** [comment]
你查看nginx配置文件中的 "resolver  114.114.114.114;"配置项，默认114.114.114.114是国内的dns服务器，你将服务器改为 "resolver  8.8.8.8;"就可以了

**Comment by Oceanlotus** [comment]
感谢，问题已解决。
