### ISSUE TITLE
能否实现静态资源缓存功能

### ISSUE THREAD

**Issue by yitu2020** [jx-sec/jxwaf#20]
能否实现静态资源缓存功能

**Comment by jx-sec** [comment]
实现是可以实现，不过意义不大，用cdn不是更好，省带宽速度还快，用户体验也更好，除非你本身就想自建cdn

**Comment by yitu2020** [comment]
> 实现是可以实现，不过意义不大，用cdn不是更好，省带宽速度还快，用户体验也更好，除非你本身就想自建cdn

刚好就是有自建cdn的需求
