### ISSUE TITLE
centos 8 test

### ISSUE THREAD

**Issue by abackerberos** [jx-sec/jxwaf#28]
when I trying to install on the Centos 8, 

when run #sudo sh install.sh
error:
No match for argument: python-devel
No match for argument: phtyon-pip

when run # pip3 install -r requirements.txt
error:
python setup.py egg-info failed with error code 1 in /tmp/pip-build-529e745d/mysqlclient

can advise how to resolve it?

thank you.

**Comment by jx-sec** [comment]
mark

**Comment by jx-sec** [comment]
It is recommended that you deploy with docker, and the relevant documentation has been updated。
docs: https://github.com/jx-sec/jxwaf/blob/master/English.md
