### ISSUE TITLE
必须配置使用阿里云存储日志？

### ISSUE THREAD

**Issue by xiaochao** [jx-sec/jxwaf#38]
配置了日志远程存储的，但是还是提示需要配置日志。
![image](https://user-images.githubusercontent.com/1953662/115207324-12264e80-a12e-11eb-9531-cf7027f9f37f.png)
![image](https://user-images.githubusercontent.com/1953662/115207369-1ce0e380-a12e-11eb-9fb0-06295b55094c.png)

**Comment by jx-sec** [comment]
不是必须 只是为了方便集成阿里云的sls服务 自己有日志服务器的话通过远程日志配置即可 通过syslog协议发送日志
