### ISSUE TITLE
函数重复运行问题

### ISSUE THREAD

**Issue by yzfshuijing** [jx-sec/jxwaf#4]
您好，看了一下您的代码，_rule_match函数会对rules进行遍历，执行
_process_request、_process_transform，_process_request每次循环都会调用，而_process_transform中rule_transform里面可能出现函数重复运行，如uriDecode，这样是不是会影响性能呢？

**Comment by jx-sec** [comment]
"而_process_transform中rule_transform里面可能出现函数重复运行，如uriDecode"，不是很清楚你表达的意思，请补充说明下。rule_transform本身的类型是table，允许接受多个预处理转换配置，比如我接受到url后，先进行uriDecode进行解码，之后调用length计算长度，具体取决于业务场景，目前没发现非配置外执行的情况，你的意思是uriDecode执行一次后在重复执行一次？

**Comment by yzfshuijing** [comment]
我的意思是比如配置项为
[{
	"rule_action": "deny",
	"rule_category": "通用基础",
	"rule_update_category": "base",
	"rule_log": "true",
	"rule_serverity": "high",
	"rule_matchs": [{
		"rule_transform": ["uriDecode", "length"],
		"rule_vars": [{
			"rule_var": "REQUEST_HEADERS",
			"rule_ignore": ["Cookie", "Referer"]
		}, {
			"rule_var": "REQUEST_HEADERS_NAMES"
		}],
		"rule_operator": "gt",
		"rule_pattern": "120",
		"rule_negated": false
	}],
	"rule_id": "1002",
	"rule_detail": "base_headers_length_detection"
}, {
	"rule_action": "deny",
	"rule_category": "通用基础",
	"rule_update_category": "base",
	"rule_log": "true",
	"rule_serverity": "high",
	"rule_matchs": [{
		"rule_transform": ["uriDecode"],
		"rule_vars": [{
			"rule_var": "ARGS"
		}, {
			"rule_var": "REQUEST_HEADERS"
		}, {
			"rule_var": "ARGS_NAMES"
		}, {
			"rule_var": "REQUEST_HEADERS_NAMES"
		}],
		"rule_operator": "rx",
		"rule_pattern": "[\\f\\n\\r\\t\\v\\x00]",
		"rule_negated": "false"
	}],
	"rule_id": "1003",
	"rule_detail": "空白字符与异常字符检测"
}]
这样rules两个table元素，遍历规则时，所以每个table都会执行_process_request、_process_transform，这样不是有点浪费性能吗？
还有我想咨询下，我们现在用libinjection，是不是想rx这种{
	"rule_action": "deny",
	"rule_category": "通用基础",
	"rule_update_category": "base",
	"rule_log": "true",
	"rule_serverity": "middle",
	"rule_matchs": [{
		"rule_transform": ["none"],
		"rule_vars": [{
			"rule_var": "REQUEST_METHOD"
		}],
		"rule_operator": "rx",
		"rule_pattern": "^(?:GET|HEAD|POST)$",
		"rule_negated": "true"
	}],
	"rule_id": "1009",
	"rule_detail": "异常method"
}正则匹配的就不需要了呢？我看从http://update.jxwaf.com/waf/update_rule 的post请求下来的json文件包含了很多的关于sql的正则匹配规则

**Comment by jx-sec** [comment]
第一个问题，之前有个提交，已经把最耗性能的local t = request.request[var.rule_var]()操作进行优化处理了，你可以去看看相关的代码，然而实测结果对性能基本上没有影响 - -，也就是说经过luajit编译后，对于现如今的CPU性能，基本没影响。目前单纯的request检查功能，一直稳定在1ms上下，哪怕一个规则也不上也是这个数据，说明1ms应该就是启动openresty本身的性能消耗了，其他waf的操作代码，对性能的影响基本上可以忽略。解决完_process_request后，_process_transform本身并没有耗性能的操作，所以浪费性能这块不用担心。而且_process_request、_process_transform的操作是必须的，属于功能需要，没有这两个功能很规则匹配操作无法做，而且数据不预先处理干净的话，会导致很多防护正则规则被绕过的可能，而如同单纯靠正则来解决这块，会导致正则巨复杂且性能较差，这个才是对性能最大的影响。
第二个问题:
你举的例子有问题 libinjection跟1009规则一个是检测SQL和XSS，一个是检查非法method。所以这个例子肯定是需要的，但是你可以根据你的业务需要进行调整。
现在对SQL主要的防护，核心是基于libinjection，在基于防护规则组中还有防止libinjection被绕过专门写的一些补充规则。"json文件包含了很多的关于sql的正则匹配规则"，这个是我从其他商业规则整来的，建议你也上，不然哪天libinjection出点啥问题，你就GG了，后面还会上机器学习的识别，这是三条防线，你如果只上libinjection防护SQL也不是说不行，只能说，不是那么好。

**Comment by yzfshuijing** [comment]
了解了，十分感谢您的讲解！
