### ISSUE TITLE
是否可以考虑支持提供离线版规则

### ISSUE THREAD

**Issue by gdbingo** [jx-sec/jxwaf#40]
近期在选型测试开源waf，打算给公司内网的web系统使用（内网不支持外连），然后在开源waf的基础上二次开发，研究jxwaf有一段时间，jxwaf是比较符合需求且功能丰富的开源waf，也知道有朋友之前提过类似的issues。还是希望作者可以考虑下是否可提供离线版的规则，满足中小型公司内部隔离网的使用需求，说白了本身不考虑商业版waf而考虑开源waf也是基于内网隔离网段的考虑。

**Comment by jx-sec** [comment]
支持离线，语义模型加载后就在本地控制台
