### ISSUE TITLE
网站分组内 增加网站 配置 开启 https强制跳转功能无效 配置完成https域名无法正常访问。

### ISSUE THREAD

**Issue by devops-utils-tools** [jx-sec/jxwaf#43]
网站分组内 增加网站 配置 开启 https强制跳转功能无效 配置完成后https域名无法正常访问。
配置
<img width="799" alt="image" src="https://user-images.githubusercontent.com/23474386/192737542-15bfda03-8606-4d1c-9239-708f124695a0.png">
完成后 重新打开 默认还是关闭状态
<img width="678" alt="image" src="https://user-images.githubusercontent.com/23474386/192737775-415ed266-06da-44e9-bf90-e4d4f87cff04.png">
http功能正常 https无法正常提供服务
<img width="893" alt="image" src="https://user-images.githubusercontent.com/23474386/192738225-71aa22a1-c621-4645-b9b1-088ebbfd8683.png">

通过 网站管理 添加网站 http和https功能正常

<img width="1470" alt="image" src="https://user-images.githubusercontent.com/23474386/192738427-58dba94b-5ade-4a7f-a9d9-fe59c5a2d890.png">

<img width="778" alt="image" src="https://user-images.githubusercontent.com/23474386/192738604-1c6f4dcf-2435-45b0-ba11-75d7a8329dfb.png">

**Comment by jx-sec** [comment]
“配置完成后https域名无法正常访问 ”   测试是正常的，网站配置的优先级高于网站组配置，同时存在的话会以网站配置为主。猜测是这种情况导致的无法访问https，能同步下配置情况吗？

**Comment by devops-utils-tools** [comment]
网站配置 网站组配置 都是单独配置的 不存在重复配置情况。

**Comment by jx-sec** [comment]
> 网站配置 网站组配置 都是单独配置的 不存在重复配置情况。

BUG已复现，SSL对网站分组的处理有问题 ，感谢！

**Comment by jx-sec** [comment]
> 网站配置 网站组配置 都是单独配置的 不存在重复配置情况。

1、前端BUG - 分组网站配置显示 强制跳转     已修复

**Comment by jx-sec** [comment]
已修复，更新到RC3即可
