### ISSUE TITLE
v2022 docker_source 部署

### ISSUE THREAD

**Issue by devops-utils-tools** [jx-sec/jxwaf#44]
https://github.com/devops-utils-tools/jxwaf-dockerfile

**Comment by jx-sec** [comment]
mark，官方支持的docker部署版本会跟正式版本一起发布。建议的话用centos7.x为底层镜像，因为一些nginx的配置会以centos为参考进行环境设置，包含后续的配套系统也是以centos7为基准，其他系统不会在测试计划内。

**Comment by jx-sec** [comment]
> https://github.com/devops-utils-tools/jxwaf-dockerfile

感谢提交，JXWAF的文档会引用该地址作为定制docker的参考

**Comment by jx-sec** [comment]
已完成
