### ISSUE TITLE
流量防护 CC攻击 人机识别 配置无效

### ISSUE THREAD

**Issue by devops-utils-tools** [jx-sec/jxwaf#46]
请问流量防护 CC攻击中 配置人机识别 图片验证码 没有作用 是我理解错误吗？
<img width="660" alt="image" src="https://user-images.githubusercontent.com/23474386/192967367-205240dd-2800-40cc-b850-aed691c45b47.png">

**Comment by jx-sec** [comment]
mark，我先看看，如果有问题会在国庆期间修复

**Comment by jx-sec** [comment]
确认BUG，已修复，可以在服务中心更新     流量防护引擎-2022-10-09  。感谢反馈 :)
