### ISSUE TITLE
日志报表如何查看

### ISSUE THREAD

**Issue by shirley04** [jx-sec/jxwaf#47]
日志报表如何查看，配置阿里云or腾讯云。这个参数填什么

**Comment by jx-sec** [comment]
文档写好了，明天发，细节看文档就可以了 docs.jxwaf.com，可以加群，发布后会在群里通知 
![image](https://user-images.githubusercontent.com/9301820/194715450-da5801a4-2023-4caf-9d27-dd6172580f2a.png)

**Comment by jx-sec** [comment]
文档已更新
