### ISSUE TITLE
部署

### ISSUE THREAD

**Issue by pioneer-hash** [jx-sec/jxwaf#49]
能用镜像部署吗？ 环境搞的我裂开了

**Comment by thankfly** [comment]
已经节点和控制台都docker 化了，可以看下这个https://github.com/jx-sec/jxwaf-docker-file

**Comment by thankfly** [comment]
3
.0.+hg0gnhhhh0ggh0hhhhgh0ghhnhgh0gh0ghhgnh0h00hn000nh0hn0hnh00hn0h0h

**Comment by pioneer-hash** [comment]
> ？ 环境搞的我裂开了

谢谢，我试一下

**Comment by thankfly** [comment]
ok，有问题可以在QQ，微信群里沟通。

**Comment by wumingpc** [comment]
docker部署了启动不起来，各种报错
