### ISSUE TITLE
jxwaf-admin好像没有开源，另外从fb上看到的otp以及业务逻辑防护方面的配置，在当前开源版本都没找到对应配置方式哦

### ISSUE THREAD

**Issue by tuhaolam** [jx-sec/jxwaf#5]

**Comment by jx-sec** [comment]
jxwaf-admin的定位是规则配置更新服务器，下个版本会支持本地配置，并且会出一个本地版本的管理中心，所以不打算开源，但是不会影响正常使用，如果开源了反而不好维护官方规则。otp以及业务逻辑防护以及自学习会在下个版本放出，时间预计是今年年底，同时文档也会完善。没啥意外的话年底会出一个正式稳定版本。

**Comment by drcayman** [comment]
@jx-sec 前排支持

**Comment by adminpass** [comment]
年底？！

**Comment by tuhaolam** [comment]
现在有按计划推出吗
