### ISSUE TITLE
自学习能力

### ISSUE THREAD

**Issue by pioneer-hash** [jx-sec/jxwaf#50]
jxwaf有自学习的能力吗？我在https://cloud.tencent.com/developer/news/249663  这个帖子里看到有涉及，不知道里面的jxwaf是不是咱这个项目

**Comment by jx-sec** [comment]
是倒是是，不过这技术很老了 - - ，我记得是18年写的 ，现在不用这套了。自学习放在wids，不放在jxwaf。两个合一起是一整套防御体系

**Comment by skifffire** [comment]
wids是开源的吗，怎么集成？

**Comment by jx-sec** [comment]
今天会放出来，开源不会直接开源，但是会少量开放
