### ISSUE TITLE
地区屏蔽移除了？可惜了这么好的功能，强烈建议恢复回去，不然总感觉缺少点什么似的，没那么完整了，mini版有些功能还是很好的

### ISSUE THREAD

**Issue by wumingpc** [jx-sec/jxwaf#54]
地区屏蔽移除了？可惜了这么好的功能，强烈建议恢复回去，这个需求和场景还是很多的，有些情况下需要，不然总感觉缺少点什么似的，没那么完整了，mini版有些功能还是很好的

**Comment by jx-sec** [comment]
mark，地域很多防CC的都有提这需求，我看看有没有更好的方案

**Comment by wumingpc** [comment]
> mark，地域很多防CC的都有提这需求，我看看有没有更好的方案

是的，很不错的一个功能，我们打算把你们的系统集成整合一下，一套很不错且完善成熟的WAF系统，之前mini版有地区屏蔽，这个很不错的，希望加回去

**Comment by shuaiZend** [comment]
> mark，地域很多防CC的都有提这需求，我看看有没有更好的方案

https://github.com/dushixiang/meteor
直接4层阻断，更好的方案

**Comment by jx-sec** [comment]
新版本已支持  JXWAF4版本
