### ISSUE TITLE
关于规则更新模式的请教

### ISSUE THREAD

**Issue by tuhaolam** [jx-sec/jxwaf#6]
$ /opt/jxwaf/nginx/sbin/nginx 启动openresty,openresty会在启动或者reload的时候自动到jxwaf管理中心拉取用户配置的最新规则
->
这里有点问题，每次更新规则都要reload配置是不是不太友好？而且如果真的放到业务环境，reload其实也是不建议的。能不能做成动态更新，通过crontab自动拉取自动更新，不用reload？

**Comment by jx-sec** [comment]
业务环境下 reload是挺保险的做法，这块你可以咨询专业的运维。规则是要预先加载进内存中的，所以crontab这种方式行不通，或者说不是行不通，更新本地规则文件后，一样需要reload。至于你担心的这个问题，代码上之前有预留的配置，不过我后面删掉了(主要是因为目前是saas模式，手动reload的话用户可以确保规则没被动过)。你可以设置更新周期，比如每半小时去检查是否有规则变动，有的话就更新规则，这个我先记录下，下个版本加上。关于规则更新，还有一个方案就是waf服务器开放接口，通过接口来更新规则，另外一种是热更新的方案，如果从稳定性安全性考虑，其实reload是最好的 ，至少我是倾向于这种偏向被动的更新方式，主动更新会引入新的风险点，虽然是比被动的方式方便得多

**Comment by tuhaolam** [comment]
我也是运维。。之前测试过高并发的情况下reload 会导致部分子进程处理失败，严重者webserver会直接卡死起不来。之前看到有些openresty+lua写的程序是支持动态加载配置的，不用reload的，所以问一下。看你这么说，reload问题也不大，保险起见。期待下一版哈。

**Comment by jx-sec** [comment]
你测的是高并发的情况下难怪说不稳定……我认识的运维都是挑个夜深人静访问少的时候reload……高并发是会丢失一些请求，这个没啥好办法。动态配置的方案挺多的，综合考虑后，目前主推的是waf定期去管理端查询并更新这种方式，从逻辑上来说也是最稳定影响最小的，还能对waf进行健康监控
