### ISSUE TITLE
现在新版不支持源码安装部署了吗？

### ISSUE THREAD

**Issue by wumingpc** [jx-sec/jxwaf#60]
没有找到相关的内容，如果是自己已经安装好了openresty基于现有环境，或者需要在生产环境中用源码部署，是否可以提供一个方案

**Comment by wumingpc** [comment]
请问能否在ubuntu22.04下运行，容器镜像基于centos内核环境吗？

**Comment by jx-sec** [comment]
1、源代码也是支持的，具体你可以看下文档  https://docs.jxwaf.com/
2、默认是centos下运行的 ubuntu22.04你可以根据情况做些适配，问题应该不大

**Comment by wumingpc** [comment]
> 1、源代码也是支持的，具体你可以看下文档  https://docs.jxwaf.com/
> 2、默认是centos下运行的 ubuntu22.04你可以根据情况做些适配，问题应该不大

好的谢谢，我发现了，之前没看网站没注意到，抱歉
