### ISSUE TITLE
zlib.so 还是libz.so?

### ISSUE THREAD

**Issue by firebroo** [jx-sec/jxwaf#9]
用lua-zlib-1.2.tar.gz编译得到是zlib.so，ffi-zlib.lua里面用的是local zlib = ffi.load(ffi.os == "Windows" and "zlib1" or "z")，所以你应该是依赖了/usr/lib64/libz.so吧，全局grep没有发现lua调用zlib.so，所以这个东西没啥用把？

**Comment by jx-sec** [comment]
这个算是个历史遗留问题,之前在response阶段 用zlib做的解压缩 但是压缩后发现跟原文有差异 所以就引入另外一个库做压缩 有小伙伴后来发现是参数的设置问题,在jxwaf2会统一起来
